login:
    resource: "@BlogBundle/Controller/UsuarioController.php"
    type:     annotation

validar:
    resource: "@BlogBundle/Controller/UsuarioController.php"
    type:     annotation

registro:
    resource: "@BlogBundle/Controller/UsuarioController.php"
    type:     annotation

logout:
    resource: "@BlogBundle/Controller/UsuarioController.php"
    type:     annotation

index_etiquetas:
    resource: "@BlogBundle/Controller/EtiquetaController.php"
    type:     annotation

add_etiquetas:
    resource: "@BlogBundle/Controller/EtiquetaController.php"
    type:     annotation

delete_etiquetas:
    resource: "@BlogBundle/Controller/EtiquetaController.php"
    type:     annotation

index_categorias:
    resource: "@BlogBundle/Controller/CategoriaController.php"
    type:     annotation

add_categorias:
    resource: "@BlogBundle/Controller/CategoriaController.php"
    type:     annotation

edit_categorias:
    resource: "@BlogBundle/Controller/CategoriaController.php"
    type:     annotation

delete_categorias:
    resource: "@BlogBundle/Controller/CategoriaController.php"
    type:     annotation

read_categorias:
    resource: "@BlogBundle/Controller/CategoriaController.php"
    type:     annotation

add_entrada:
    resource: "@BlogBundle/Controller/EntradaController.php"
    type:     annotation

delete_entrada:
    resource: "@BlogBundle/Controller/EntradaController.php"
    type:     annotation

edit_entrada:
    resource: "@BlogBundle/Controller/EntradaController.php"
    type:     annotation

detalle_entrada:
    resource: "@BlogBundle/Controller/EntradaController.php"
    type:     annotation