BlogBundle\Entity\Usuario:
    type: entity
    table: usuarios
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rol:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        apellido:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        pass:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
